<?php

namespace SiteStudio\Package\GitLab;

class ConfigInitializer {

  /**
   * Src Package.
   *
   * @var string
   */
  protected $srcPackageRepo;

  /**
   * Target Package.
   *
   * @var string
   */
  protected $tarPackageRepo;

  /**
   * Src Branch or Tag.
   *
   * @var string
   */
  protected $srcBranchTag;

  /**
   * Target branch or tag.
   *
   * @var string
   */
  protected $tarBranchTag;

  /**
   * GitLab API Path.
   *
   * @var string
   */
  protected $gitlabApiPath;

  /**
   * Package Repo Group.
   *
   * @var string
   */
  protected $packageRepoGroup;

  /**
   * Comparison Folder - To store the report output.
   *
   * @var string
   */
  protected $comparisonFolder = 'package-comparison';

  /**
   * Projects Details. Autogenerated from given Project Repo.
   *
   * @var string
   */
  protected $projectsPath = "projects.json";

  /**
   * Access Token - Personal Access Token to access repo API.
   *
   * @var string
   */
  protected $accessToken;

  /**
   * ConfigInitializer constructor.
   */
  public function __construct() {
    $this->invokeUserChoice();
  }

  /**
   * Call for User options.
   */
  protected function invokeUserChoice() {
    $this->gitlabApiPath = readline('Please provide gitlab api path');
    $this->packageRepoGroup = readline('Please provide Gitlab Package Repo Group ID');
    $this->srcPackageRepo = readline('Please provide Source Package Repo');
    $this->tarPackageRepo = readline('Please provide Target Package Repo');

    $this->srcBranchTag = readline('Please provide Source Branch or Tag');
    $this->tarBranchTag = readline('Please provide Target Branch or Tag');
  }

}
